"""empty message

Revision ID: cd7f97bf4fb1
Revises: 0763d677d453
Create Date: 2026-03-17 03:21:32.924042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7f97bf4fb1'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videojuego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=150), nullable=False),
    sa.Column('consolas', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videojuego')
    # ### end Alembic commands ###
